name:                masterduel-readability
version:             0.1.0.0
github:              "mtamc/masterduel-readability"
license:             BSD3
author:              "mtamc"
maintainer:          "mtamc"
copyright:           "2023 mtamc"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <url_here>

dependencies:
- base-noprelude
- relude
- base-unicode-symbols
- hspec
- hspec-contrib
- text
- containers
- lens
- generic-lens
- mtl
- template-haskell
- data-default
- safe-exceptions
- directory
- filepath
- bytestring
- binary
- aeson-pretty
- aeson
- MissingH
- utf8-string
- pcre-heavy
- pcre-light
- megaparsec
- extra

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments
- DataKinds
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  masterduel-readability-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
    - masterduel-readability

tests:
  masterduel-readability-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - masterduel-readability-exe
